C:28:"Guzzle\Http\Message\Response":5459:{{"status":202,"body":"{\"final_task_id\": \"a876e894-a28a-11e4-b955-bc764e100926\", \"finished_at\": 1421967714.423387, \"params\": {\"organization_id\": \"Test Me\"}, \"result\": \"failed\", \"role\": \"owner\", \"site_id\": \"4ff603ab-57cd-4b66-aebd-781a58e3b3fd\", \"task_ids\": [\"a876e894-a28a-11e4-b955-bc764e100926\"], \"type\": \"remove_site_organization_membership\", \"user_id\": \"dca4f8cd-9ec2-4117-957f-fc5230c23737\", \"waiting_for_task_id\": \"a876e894-a28a-11e4-b955-bc764e100926\", \"id\": \"a876d5ca-a28a-11e4-b955-bc764e100926\", \"key\": \"1421967600\", \"environment\": null, \"environment_id\": null, \"keep_forever\": false, \"created_at\": 1421967714.350433, \"total_time\": 0.07295393943786621, \"active_description\": \"Removed site organization membership\", \"description\": \"Remove site organization membership.\", \"final_task\": {\"environment\": null, \"fn_name\": \"trigger_task\", \"has_error\": true, \"params\": {\"organization_id\": \"Test Me\", \"task_type\": \"remove_site_organization_membership\", \"site_id\": \"4ff603ab-57cd-4b66-aebd-781a58e3b3fd\"}, \"queued_at\": 1421967714.402134, \"responses\": [{\"body\": \"Traceback (most recent call last):\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/yggdrasil_tasks.py\\\", line 1891, in _trigger\\n    d.addCallbacks(executeCallback, failureCallback)\\n  File \\\"\/usr\/lib64\/python2.7\/site-packages\/twisted\/internet\/defer.py\\\", line 290, in addCallbacks\\n    self._runCallbacks()\\n  File \\\"\/usr\/lib64\/python2.7\/site-packages\/twisted\/internet\/defer.py\\\", line 551, in _runCallbacks\\n    current.result = callback(current.result, *args, **kw)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/yggdrasil_tasks.py\\\", line 1853, in executeCallback\\n    d = defer.maybeDeferred(response, workflow=workflow, task=task, **params)\\n--- <exception caught here> ---\\n  File \\\"\/usr\/lib64\/python2.7\/site-packages\/twisted\/internet\/defer.py\\\", line 134, in maybeDeferred\\n    result = f(*args, **kw)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/yggdrasil_tasks.py\\\", line 397, in remove_site_organization_membership\\n    membership = collection.retrieve(organization_id)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/backends\/cassandra\/collection.py\\\", line 729, in retrieve\\n    normalized_id = self.normalize_id(model_id)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/models\/memberships.py\\\", line 312, in normalize_id\\n    return uuid.UUID(str(model_id))\\n  File \\\"\/usr\/lib64\/python2.7\/uuid.py\\\", line 134, in __init__\\n    raise ValueError('badly formed hexadecimal UUID string')\\nexceptions.ValueError: badly formed hexadecimal UUID string\\n\", \"code\": 500}], \"result\": \"failed\", \"site_id\": \"4ff603ab-57cd-4b66-aebd-781a58e3b3fd\", \"started_at\": 1421967714.402135, \"user_id\": \"dca4f8cd-9ec2-4117-957f-fc5230c23737\", \"workflow_id\": \"a876d5ca-a28a-11e4-b955-bc764e100926\", \"id\": \"a876e894-a28a-11e4-b955-bc764e100926\", \"key\": \"1421967600\", \"created_at\": 1421967714.350914, \"queued_time\": 9.5367431640625e-07, \"run_time\": null, \"phase\": \"started\", \"allow_concurrent\": false, \"total_time\": null, \"messages\": {\"2015-01-22T23:01:54.462095\": {\"message\": \"Traceback (most recent call last):\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/yggdrasil_tasks.py\\\", line 1891, in _trigger\\n    d.addCallbacks(executeCallback, failureCallback)\\n  File \\\"\/usr\/lib64\/python2.7\/site-packages\/twisted\/internet\/defer.py\\\", line 290, in addCallbacks\\n    self._runCallbacks()\\n  File \\\"\/usr\/lib64\/python2.7\/site-packages\/twisted\/internet\/defer.py\\\", line 551, in _runCallbacks\\n    current.result = callback(current.result, *args, **kw)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/yggdrasil_tasks.py\\\", line 1853, in executeCallback\\n    d = defer.maybeDeferred(response, workflow=workflow, task=task, **params)\\n--- <exception caught here> ---\\n  File \\\"\/usr\/lib64\/python2.7\/site-packages\/twisted\/internet\/defer.py\\\", line 134, in maybeDeferred\\n    result = f(*args, **kw)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/yggdrasil_tasks.py\\\", line 397, in remove_site_organization_membership\\n    membership = collection.retrieve(organization_id)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/backends\/cassandra\/collection.py\\\", line 729, in retrieve\\n    normalized_id = self.normalize_id(model_id)\\n  File \\\"\/usr\/lib\/python2.7\/site-packages\/titan\/yggdrasil\/models\/memberships.py\\\", line 312, in normalize_id\\n    return uuid.UUID(str(model_id))\\n  File \\\"\/usr\/lib64\/python2.7\/uuid.py\\\", line 134, in __init__\\n    raise ValueError('badly formed hexadecimal UUID string')\\nexceptions.ValueError: badly formed hexadecimal UUID string\\n\", \"level\": \"ERROR\"}}}}","headers":{"Server":["nginx"],"Date":["Thu, 22 Jan 2015 23:01:54 GMT"],"Content-Type":["application\/json"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"X-Pantheon-Trace-Id":["62e73fb6-dbcf-4d2f-bc2b-50ab7b323a7d"],"X-Frame-Options":["deny"],"Access-Control-Allow-Origin":["https:\/\/dashboard.getpantheon.com"],"Access-Control-Allow-Methods":["GET"],"Access-Control-Allow-Headers":["Origin, Content-Type, Accept"],"Vary":["Accept-Encoding"]}}}